### ISSUE TITLE
Sample `experimental/context_menus` failing on Flutter 3.16beta and above

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#2086] opened 2023-11-12 03:47 UTC
```console
❌ /home/runner/work/samples/samples/experimental/context_menus/test/field_types_page_test.dart: Gives correct behavior for all values of contextMenuBuilder (variant: TargetPlatform.iOS) (failed)
  
  Warning: A call to tap() with finder "Found 1 widget with type "EditableText" (ignoring all but first): [
    EditableText(controller: TextEditingController#db838(TextEditingValue(text: ┤EditableText doesn't show any selection menu by itself, even when contextMenuBuilder is passed.├, selection: TextSelection.invalid, composing: TextRange(start: -1, end: -1))), focusNode: FocusNode#b9358, debugLabel: (blackMountainView displayMedium).apply, inherit: true, color: Color(0xff000000), family: Roboto, decoration: Color(0xff000000) TextDecoration.none, textAlign: start, maxLines: 3, keyboardType: TextInputType(name: TextInputType.multiline, signed: null, decimal: null), autofillHints: [], dependencies: [Directionality, MediaQuery, ScrollConfiguration, _EffectiveTickerMode], state: EditableTextState#89914(tickers: tracking 1 ticker)),
  ]" derived an Offset (Offset(400.0, 548.0)) that would not hit test on the specified widget.
  Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
  The finder corresponds to this RenderBox: _RenderCompositionCallback#16eb0 relayoutBoundary=up6
  The hit test result at that offset is: HitTestResult(_RenderInkFeatures#8567a@Offset(200.0, 211.0), RenderCustomPaint#4051d@Offset(200.0, 211.0), RenderPhysicalShape#bed60@Offset(200.0, 211.0), RenderConstrainedBox#caeb7@Offset(200.0, 211.0), RenderCustomSingleChildLayoutBox#ae454@Offset(392.0, 540.0), RenderPadding#8a905@Offset(400.0, 548.0), RenderAnimatedOpacity#c185d@Offset(400.0, 548.0), RenderTapRegion#cd176@Offset(400.0, 548.0), _RenderTheater#542b8@Offset(400.0, 548.0), RenderAbsorbPointer#ec0d9@Offset(400.0, 548.0), RenderPointerListener#c14cc@Offset(400.0, 548.0), RenderSemanticsAnnotations#c3917@Offset(400.0, 548.0), RenderSemanticsAnnotations#44a54@Offset(400.0, 548.0), RenderSemanticsAnnotations#3cb49@Offset(400.0, 548.0), RenderTapRegionSurface#761af@Offset(400.0, 548.0), RenderSemanticsAnnotations#fc83f@Offset(400.0, 548.0), RenderSemanticsAnnotations#8c412@Offset(400.0, 548.0), RenderSemanticsAnnotations#76349@Offset(400.0, 548.0), RenderSemanticsAnnotations#88400@Offset(400.0, 548.0), HitTestEntry<HitTestTarget>#00ed3(_ReusableRenderView#c0059), HitTestEntry<HitTestTarget>#e5ddb(<AutomatedTestWidgetsFlutterBinding>))
  #0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1409:25)
  #1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1292:12)
  #2      WidgetController.tap (package:flutter_test/src/controller.dart:613:18)
  #3      main.<anonymous closure> (file:///home/runner/work/samples/samples/experimental/context_menus/test/field_types_page_test.dart:144:20)
  <asynchronous suspension>
  #4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
  <asynchronous suspension>
  #5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
  <asynchronous suspension>
  #6      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:42)
  <asynchronous suspension>
  To silence this warning, pass "warnIfMissed: false" to "tap()".
  To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.
  
  ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
  The following TestFailure was thrown running a test:
  Expected: no matching candidates
    Actual: _TypeWidgetFinder:<Found 1 widget with type "DesktopTextSelectionToolbar": [
              DesktopTextSelectionToolbar(dependencies: [MediaQuery]),
            ]>
     Which: means one was found but none were expected
  
  When the exception was thrown, this was the stack:
  #4      main.<anonymous closure> (file:///home/runner/work/samples/samples/experimental/context_menus/test/field_types_page_test.dart:146:7)
  <asynchronous suspension>
  #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
  <asynchronous suspension>
  #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
  <asynchronous suspension>
  <asynchronous suspension>
  (elided one frame from package:stack_trace)
  
  This was caught by the test expectation on the following line:
    file:///home/runner/work/samples/samples/experimental/context_menus/test/field_types_page_test.dart line 146
  The test description was:
    Gives correct behavior for all values of contextMenuBuilder (variant: TargetPlatform.iOS)
  ════════════════════════════════════════════════════════════════════════════════════════════════════
  Test failed. See exception logs above.
  The test description was: Gives correct behavior for all values of contextMenuBuilder (variant: TargetPlatform.iOS)
```

**Comment by domesticmouse** [comment] 2023-11-12 04:46
Also:

```console
00:02 +6: /Users/brettmorgan/Documents/GitHub/samples/experimental/context_menus/test/cascading_menu_page_test.dart: Can show and use the cascading menu
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching candidates
  Actual: _TypeWidgetFinder:<Found 1 widget with type "DesktopTextSelectionToolbar": [
            DesktopTextSelectionToolbar(dependencies: [MediaQuery]),
          ]>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/brettmorgan/Documents/GitHub/samples/experimental/context_menus/test/cascading_menu_page_test.dart:121:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/brettmorgan/Documents/GitHub/samples/experimental/context_menus/test/cascading_menu_page_test.dart line 121
The test description was:
  Can show and use the cascading menu
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +6 -1: /Users/brettmorgan/Documents/GitHub/samples/experimental/context_menus/test/cascading_menu_page_test.dart: Can show and use the cascading menu [E]
  Test failed. See exception logs above.
  The test description was: Can show and use the cascading menu
  

To run this test again: /Users/brettmorgan/flutter/bin/cache/dart-sdk/bin/dart test /Users/brettmorgan/Documents/GitHub/samples/experimental/context_menus/test/cascading_menu_page_test.dart -p vm --plain-name 'Can show and use the cascading menu'
00:03 +12 ~6 -1: Some tests failed.                
```

**Comment by justinmc** [comment] 2024-01-05 21:08
Is this a duplicate of https://github.com/flutter/samples/issues/2110, closed with https://github.com/flutter/samples/pull/2134?

**Comment by domesticmouse** [comment] 2024-01-06 00:34
I think it was a different test that I disabled. If you re-enabled all the tests in your PR, feel free to close this bug as fixed.

**Closed** 2024-02-19 23:27 UTC
Labels: p1
