### ISSUE TITLE
multiple_flutters_android not found

### ISSUE THREAD

**Issue by zsunkun** [flutter/samples#755] opened 2021-03-05 12:49 UTC
There is no multiple_flutters_android directory on the master branch.
https://github.com/flutter/samples/blob/master/add_to_app/multiple_flutters/multiple_flutters_android/README.md   get 404

**Comment by xster** [comment] 2021-03-05 15:23
@gaaclarke let's merge https://github.com/flutter/samples/pull/677

**Comment by zhouxin1233** [comment] 2021-03-08 02:18
看来又是个吹牛逼的ppt， 说好的降低99%呢

**Comment by xster** [comment] 2021-03-08 17:37
@zhouxin1233 please see our code of conduct at https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md and use productive language to help everyone move forward.

**Comment by gaaclarke** [comment] 2021-03-08 18:11
Landed.

**Closed by gaaclarke** 2021-03-08 18:11 UTC

**Comment by zhouxin1233** [comment] 2021-03-09 03:04
> @zhouxin1233 please see our code of conduct at https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md and use productive language to help everyone move forward.

2021-03-09 11:01:20.706 21297-21297/dev.flutter.multipleflutters E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.flutter.multipleflutters, PID: 21297
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.flutter.multipleflutters/dev.flutter.multipleflutters.SingleFlutterActivity}: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3762)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalStateException: Failed to spawn new JNI connected shell from existing shell.
        at io.flutter.util.Preconditions.checkState(Preconditions.java:52)
        at io.flutter.embedding.engine.FlutterJNI.spawn(FlutterJNI.java:342)
        at io.flutter.embedding.engine.FlutterEngine.spawn(FlutterEngine.java:383)
        at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:101)
        at dev.flutter.multipleflutters.EngineBindings.<init>(EngineBindings.kt:45)
        at dev.flutter.multipleflutters.SingleFlutterActivity$engineBindings$2.invoke(SingleFlutterActivity.kt:16)
        at dev.flutter.multipleflutters.SingleFlutterActivity$engineBindings$2.invoke(SingleFlutterActivity.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dev.flutter.multipleflutters.SingleFlutterActivity.getEngineBindings(Unknown Source:2)
        at dev.flutter.multipleflutters.SingleFlutterActivity.provideFlutterEngine(SingleFlutterActivity.kt:30)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:227)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:155)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
        at dev.flutter.multipleflutters.SingleFlutterActivity.onCreate(SingleFlutterActivity.kt:20)
        at android.app.Activity.performCreate(Activity.java:8183)
        at android.app.Activity.performCreate(Activity.java:8167)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3735)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
