### ISSUE TITLE
filipino_cuisine just loads grey screen

### ISSUE THREAD

**Issue by eseidel** [flutter/samples#467] opened 2020-06-10 02:56 UTC
https://flutter.github.io/samples/web/filipino_cuisine/#/

Google Chrome | 83.0.4103.61 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1903 (Build 18362.836)

![image](https://user-images.githubusercontent.com/478541/84221976-41d6e580-aa8b-11ea-93b1-8c1c7a45e173.png)

**Comment by eseidel** [comment] 2020-06-10 03:06
Looks like the top-level object got changed from a List to a map in https://filipino-cuisine-app.firebaseio.com/data.json, which is why it's breaking.

**Comment by eseidel** [comment] 2020-06-10 03:20
I briefly tried to fix it.  The top level json has non-list items in it (representing payments it seems?) so there is just a definite mis-match between what the code expects and what the server is responding.

**Comment by guidezpl** [comment] 2021-07-27 09:01
I'm seeing a loading indicator and the following error
<img width="1275" alt="Screenshot 2021-07-27 at 11 01 32" src="https://user-images.githubusercontent.com/6655696/127127043-553ad85f-34df-431c-93d7-3e564f1b27b5.png">

**Comment by RedBrogdon** [comment] 2021-07-28 21:25
Thanks for calling this out, @guidezpl. 

This sample needs to be removed from the repo at this point. It was intended as a showcase for Flutter on the web, which is no longer strictly necessary.

**Comment by Pyrolistical** [comment] 2021-09-15 18:10
caused by https://github.com/markgrancapal/filipino_cuisine/issues/3

**Comment by amanv8060** [comment] 2022-02-25 19:41
@guidezpl can this be closed ,  fixed by https://github.com/flutter/samples/pull/923 ?

**Comment by johnpryan** [comment] 2022-02-25 22:20
Yes this can be closed now that filipino_cuisine is gone.

**Closed by johnpryan** 2022-02-25 22:20 UTC
Labels: bug, p0
