### ISSUE TITLE
Login Screen Error

### ISSUE THREAD

**Issue by mohak852** [flutter/samples#531] opened 2020-08-22 20:24 UTC
In the provider_shopper the login screen has some layout problem. I am attaching one screenshot with this issue. I am working on this pr.

![WhatsApp Image 2020-08-23 at 1 37 52 AM](https://user-images.githubusercontent.com/58987025/90965183-9e22a080-e4e3-11ea-8836-36ed291824c0.jpeg)

**Comment by AyushBherwani1998** [comment] 2020-08-24 05:42
Hey @mohak852, thanks for reporting this but unfortunately I'm not able to reproduce this locally on flutter version `1.20.2`. It's a strange issue given that the `Text` uses `headline1` TextTheme which already has a predefined font size of 112. 

On which emulator are you running the sample, also can you please provide which flutter version are you using to run the sample?

**Comment by mohak852** [comment] 2020-08-26 14:24
I am running flutter 1.17.3 and i have tried on emulator and real device both  are showing the same error.But when we wrap this in FittedBox the error goes away i think we should do this.

**Comment by AyushBherwani1998** [comment] 2020-08-28 06:16
Can you upgrade the Flutter to the latest stable version? If `headline1` is not respecting the given `fontSize` then it's a bug in the framework, which I don't have a strong feeling about.

**Comment by mohak852** [comment] 2020-08-28 06:57
Now its working after upgrading to the latest version. Thank you @AyushBherwani1998 For helping me

**Comment by AyushBherwani1998** [comment] 2020-08-28 07:28
Awesome! I guess we can close the issue 🎉

**Closed** 2020-08-28 18:53 UTC
