### ISSUE TITLE
Web-specific issues with "Material 3 - Flutter WasmGC Preview"

### ISSUE THREAD

**Issue by tomayac** [flutter/samples#2069] opened 2023-10-26 10:45 UTC
Tested on `120.0.6089.3 (Official Build) canary (arm64)`.

- **Scrolling:** The scrollbar resizes when scrolling down, as if new content were lazily loaded.
   https://github.com/flutter/samples/assets/145676/d0a2146a-520b-4f71-951f-a86b6ee770ef
- **Tabbing:** The tab order is off.
   https://github.com/flutter/samples/assets/145676/578bd859-1376-4017-a8a8-78d687fed1b1
- **Popover positioning:** When there's not enough space to show the popover, the popover flashes and then disappears.
   https://github.com/flutter/samples/assets/145676/87e25d9a-4fe3-4669-b8eb-9a3f45f6cb2b
- **Text editing:** Text editing swallows entered text.
   https://github.com/flutter/samples/assets/145676/a3c384b9-16d1-4688-8558-a9be825a825e
   https://github.com/flutter/samples/assets/145676/e7401cf5-ccb8-486d-a105-dd090cec6594

**Comment by parlough** [comment] 2023-10-26 15:05
Thanks for the videos showcasing the issues!

Just to confirm, did you access the sample at https://flutterweb-wasm.web.app/, somewhere your else, or build it yourself with a recent Flutter build? On Chrome 120 I'm only able to get the WASM sample running by building myself with the latest Flutter `main` builds.

I think outside of the text editing issues, these issues exist in some form on the JS version of the demo too. \cc @QuncCccccc 

I can't seem to reproduce the text editing issues on the JS version nor by building myself on the latest `main` on `Version 120.0.6090.1 (Official Build) canary (arm64)`. 

\cc @kevmoo

**Comment by tomayac** [comment] 2023-10-26 15:13
This was tested with the URL you can find in this [Google Doc](https://docs.google.com/document/d/1Pmi7nkbXumzp5cqvFPxsZQq55a2RNsRkNZEVPpFLljc/edit). Please ask for access, since it's not yet public.

**Comment by kevmoo** [comment] 2023-10-26 15:27
We should compare with https://flutter.github.io/samples/web/material_3_demo/

To see if these are issues with the Wasm work, or just issues with the demo/widgets!

**Comment by parlough** [comment] 2023-10-26 15:38
Thanks for the link! Clarifying for the issue that these videos are with skwasm.

I can reproduce the scrolling and tabbing issues with the original JS version.

The popover behavior does seem to have more issues in the linked version and the text issues are unique to this version as well. They don't occur on a wasm build with CanvasKit either.

**Comment by tomayac** [comment] 2023-10-26 15:39
All videos and reported issues stem from the version linked in the Google Doc experienced in `120.0.6089.3 (Official Build) canary (arm64)`.

**Comment by domesticmouse** [comment] 2023-11-01 03:27
Who should I assign this issue to?

**Comment by kevmoo** [comment] 2023-11-01 16:20
@domesticmouse – we need to figure out if this is a widget issue or a flutter wasm issue.

So...I'm not sure. It'd be great to have our flutter/flutter triage person take a stab.

**Comment by QuncCccccc** [comment] 2023-11-01 16:55
Hi! 

The scrolling behavior is intended. We compute the scroll bar height when more content shows up for the first time and cache the height. So after that, the scroll bar height should be fixed!

I can reproduce the popover positioning problem. I think it's a widget issue. I will take a look:) !

For the other two issue, I cannot reproduce them.

**Comment by domesticmouse** [comment] 2023-11-17 01:20
@kevmoo assigning this to you to chase down the issues @QuncCccccc can't repro

**Comment by parlough** [comment] 2023-12-23 22:55
Closing in favor of https://github.com/flutter/samples/issues/2129, where I'm tracking this and other issues more specifically. Thanks all!

**Closed by parlough** 2023-12-23 22:55 UTC
Labels: p2
