### ISSUE TITLE
[slide_puzzle] error while running slide_puzzle

### ISSUE THREAD

**Issue by AjayThakur12** [flutter/samples#409] opened 2020-04-06 09:21 UTC
**Description**
-----------------------------------------------------------------------------------------------------------------
while running slide puzzle project getting this error :
` Compiler message:`  
`lib/src/widgets/decoration_image_plus.dart:10:7: Error: The non-abstract class 'DecorationImagePlus' is missing implementations for these members:`
` - DecorationImage.onError`

**Comment by AjayThakur12** [comment] 2020-04-07 02:00
@RedBrogdon  Can i work on this issue

**Comment by johnpryan** [comment] 2020-04-07 02:51
@AjayThakur12 Could you create a pull request to the original [slide_puzzle](https://github.com/kevmoo/slide_puzzle) repo instead? The copy here is only committed for historical reasons (we should probably convert it to a submodule.)

The problem is that slide_puzzle doesn't support your SDK yet. The `DecorationImage` class added a new method (`onError`) and it needs to be added out [here](https://github.com/kevmoo/slide_puzzle/blob/master/lib/src/widgets/decoration_image_plus.dart.

It's also helpful to include the version of Flutter that you're using. (In this case, the breaking change happened [12 days ago](https://github.com/flutter/flutter/pull/53329), so you're probably on the master channel.)

**Closed** 2020-04-07 02:51 UTC
