### ISSUE TITLE
Google Map Unresponsive - White/Blank screen in Place Tracker App.

### ISSUE THREAD

**Issue by bajajsahil** [flutter/samples#532] opened 2020-08-23 08:10 UTC
I am seeing the white/blank screen issue when

1. I switch between apps
2. I open the camera on top of google map and comes back. (see steps - https://github.com/flutter/flutter/issues/39797#issuecomment-664171459)

This issue is coming in the official place tracker app and in my own app which uses google map plugin.

### Place Tracker APP

![Screenshot_20200818-233446](https://user-images.githubusercontent.com/19187821/90974128-e1156000-e545-11ea-91ed-093ae13794bb.jpg)

### My APP

![Screenshot_20200818-233420](https://user-images.githubusercontent.com/19187821/90974156-2043b100-e546-11ea-9429-e556834efb52.jpg)

_**google_maps_flutter**_ - 0.5.30

**_flutter doctor -v_**

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.17134.165], locale en-IN)
    • Flutter version 1.20.1 at \mine\fultter\flutter
    • Framework revision 2ae34518b8 (2 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at \mine\install\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = \mine\install\AndroidSDK
    • Java binary at: \mine\install\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at \mine\install\Android Studio
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM G960F (mobile) • 231173e32f027ece • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by bajajsahil** [comment] 2020-08-25 12:10
If anyone facing this issue, then I found a workaround for now until this is fixed.

```dart
  @override
  Future<Null> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        //Resetting the map style on app resume to so that map appears again.
        mapController.future.then((controller) => controller.setMapStyle(null));
        break;
    }
  }
```
Hope it helps.

**Comment by domesticmouse** [comment] 2020-08-29 08:13
Closing out this bug as a duplicate of https://github.com/flutter/flutter/issues/64568

**Closed by domesticmouse** 2020-08-29 08:13 UTC
